(*==================================*)
(*  ConstraintComponentToLightcone  *)
(*==================================*)

ConstraintComponentToLightcone[ConstraintComponent_]:=Catch@Module[{Constraint},
Constraint=ConstraintComponent/.SourcePO3Activate;
Constraint=Constraint/.SourcePerpO3Activate;
Constraint=Constraint/.PADMPiActivate;
Constraint=Constraint/.PO3PiActivate;
Constraint=Constraint/.PADMActivate;
Constraint=Constraint/.SourceCompose;
Constraint=xAct`xCoba`SeparateBasis[AIndex][Constraint];
Constraint=Constraint//NoScalar;
Constraint=Constraint/.ToP;
Constraint=Constraint/.SourceCompose;
Constraint=xAct`xCoba`SeparateBasis[AIndex][Constraint];
Constraint=Constraint//NoScalar;
Constraint=Constraint/.ToP;
Constraint=Constraint//ToNewCanonical;
Constraint=Constraint//NoScalar;
Constraint=Constraint/.ToV;
Constraint=Constraint//ToNewCanonical;
Constraint=Constraint//NoScalar;
Constraint=Constraint/.ToP;
Constraint=xAct`xCoba`SeparateBasis[AIndex][Constraint];
Constraint=Constraint//NoScalar;
Constraint=Constraint/.ToP;
Constraint=Constraint//NoScalar;
Constraint=xAct`xCoba`SeparateBasis[cartesian][Constraint];
Constraint=Constraint//NoScalar;
Constraint=Constraint/.ToP;
Constraint=Constraint//xAct`xCoba`ContractBasis;
Constraint=Constraint//ScreenDollarIndices;
Constraint=Constraint//NoScalar;
Constraint=SeparateMetric[G][Evaluate@Constraint];
Constraint=xAct`xCoba`SeparateBasis[cartesian][Constraint];
Constraint=Constraint//NoScalar;
Constraint=Constraint//xAct`xCoba`ContractBasis;
Constraint=Constraint//NoScalar;
Constraint=Constraint//xAct`xCoba`TraceBasisDummy;
Constraint=Constraint/.xAct`xCoba`TensorValues[P];
Constraint=Constraint/.xAct`xCoba`TensorValues[G];
Constraint=Constraint/.xAct`xCoba`TensorValues[Tau];
Constraint=Constraint/.xAct`xCoba`TensorValues[Sigma];
Constraint=Constraint/.{Def->Sqrt[En^2-Mo^2]};
Constraint=Constraint/(2*3*5*7*11*En Mo)^10;
Constraint=Constraint//Together;
Constraint=Constraint//Numerator;
Constraint=Constraint//CollectTensors;
Print@Constraint;
Constraint==0];
