(*===========================*)
(*  MassiveAnalysisOfSector  *)
(*===========================*)

MassiveAnalysisOfSector[RawSector_,SourceComponentsToFreeSourceVariables_List]:=Catch@Module[{PrintVariable,Sector},
PrintVariable={};
PrintVariable=PrintVariable~Append~PrintTemporary@" ** MassiveAnalysisOfSector...";
Sector=RawSector//NoScalar;
Sector=Sector/.SourcePO3Activate;
Sector=Sector//NoScalar;
Sector=Sector//ToNewCanonical;
Sector=Sector/.SourcePerpO3Activate;
Sector=Sector//NoScalar;
Sector=Sector//ToNewCanonical;
Sector=Sector/.PADMPiActivate;
Sector=Sector//NoScalar;
Sector=Sector//ToNewCanonical;
Sector=Sector/.PO3PiActivate;
Sector=Sector//NoScalar;
Sector=Sector//ToNewCanonical;
Sector=Sector/.PADMActivate;
Sector=Sector//NoScalar;
Sector=Sector//ToNewCanonical;
Sector=Sector/.SourceCompose;
Sector=xAct`xCoba`SeparateBasis[AIndex][Sector];
Sector=Sector/.ToP;
Sector=Sector/.SourceCompose;
Sector=xAct`xCoba`SeparateBasis[AIndex][Sector];
Sector=Sector/.ToP;
Sector=Sector//NoScalar;
Sector=Sector//ToNewCanonical;
Sector=Sector/.ToV;
Sector=Sector//ToNewCanonical;
Sector=Sector/.ToP;
Sector=xAct`xCoba`SeparateBasis[AIndex][Sector];
Sector=Sector//NoScalar;
Sector=Sector/.ToP;
Sector=Sector//ToNewCanonical;
Sector=Sector//NoScalar;
PrintVariable=PrintVariable~Append~PrintTemporary[" ** SeparateMetric..."];
Sector=SeparateMetric[G][Evaluate@Sector];
PrintVariable=PrintVariable~Append~PrintTemporary[" ** SeparateBasis..."];
Sector=xAct`xCoba`SeparateBasis[cartesian][Sector];
PrintVariable=PrintVariable~Append~PrintTemporary[" ** ContractBasis..."];
Sector=Sector//xAct`xCoba`ContractBasis;
PrintVariable=PrintVariable~Append~PrintTemporary[" ** TraceBasisDummy..."];
Sector=Sector//xAct`xCoba`TraceBasisDummy;
PrintVariable=PrintVariable~Append~PrintTemporary[" ** TensorValues..."];
Sector=Sector/.xAct`xCoba`TensorValues[P];
Sector=Sector/.xAct`xCoba`TensorValues[G];
Sector=Sector/.xAct`xCoba`TensorValues[Tau];
Sector=Sector/.xAct`xCoba`TensorValues[Sigma];
Sector=Sector/.xAct`xCoba`TensorValues[Dagger@Tau];
Sector=Sector/.xAct`xCoba`TensorValues[Dagger@Sigma];
Sector=Sector/.{Def->Sqrt[En^2-Mo^2]};
Sector=Sector//Together;
PrintVariable=PrintVariable~Append~PrintTemporary[" ** Imposing conserved sources..."];
Sector=Sector/.SourceComponentsToFreeSourceVariables;
Sector=Sector//Together;
NotebookDelete@PrintVariable;
Print@" ** ParticleSpectrum: massive mode contribution from given spin-parity sector in the lightcone basis:";
Print@Sector;
Sector];
