(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code::Initialization:: *)
DefBasis[cartesian,TangentM4,{0,1,2,3},BasisColor->RGBColor[0,1,0]];


(* ::Code::Initialization:: *)
EnSymb="\[ScriptCapitalE]";
DefConstantSymbol[En,PrintAs->SymbolBuild@EnSymb];


(* ::Code::Initialization:: *)
MoSymb="\[ScriptP]";
DefConstantSymbol[Mo,PrintAs->SymbolBuild@MoSymb];


(* ::Code::Initialization:: *)
AllComponentValues[P[{a,cartesian}],{En,0,0,Mo}];
AllComponentValues[P[{-a,-cartesian}],{En,0,0,-Mo}];
ClearBuild[];


(* ::Code::Initialization:: *)
AllComponentValues[G[{a,cartesian},{b,cartesian}],DiagonalMatrix@{1,-1,-1,-1}];
AllComponentValues[G[{-a,-cartesian},{-b,-cartesian}],DiagonalMatrix@{1,-1,-1,-1}];
ClearBuild[];


(* ::Code::Initialization:: *)
AllComponentValues[Tau[{-a,-cartesian},{-b,-cartesian}]];
AllComponentValues[Evaluate@Dagger@Tau[{-a,-cartesian},{-b,-cartesian}]];
ClearBuild[];


(* ::Code::Initialization:: *)
AllComponentValues[Sigma[{-a,-cartesian},{-b,-cartesian},{-c,-cartesian}]];
AllComponentValues[Evaluate@Dagger@Sigma[{-a,-cartesian},{-b,-cartesian},{-c,-cartesian}]];
ClearBuild[];


(* ::Code::Initialization:: *)
(AllComponentValues@FreeToBasis[cartesian]@#;ClearBuild[];)&/@{TauP1p[a,b],SigmaP1p[a,b],SigmaPerp1p[a,b],TauP1m[a],SigmaP1m[a],TauPerp1m[a],SigmaPerp1m[a],TauP2p[a,b],SigmaP2p[a,b],SigmaP2m[a,b,c],TauP1p[-a,-b],SigmaP1p[-a,-b],SigmaPerp1p[-a,-b],TauP1m[-a],SigmaP1m[-a],TauPerp1m[-a],SigmaPerp1m[-a],TauP2p[-a,-b],SigmaP2p[-a,-b],SigmaP2m[-a,-b,-c]};
